name: Super-Linter

on: push

jobs: 
  super-linter:
    name: Lint code base
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v4.9.5
        env: 
          DEFAULT_BRANCH: github-action-implement
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}